name: github-actions-workflow-name
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs: 
  check-nodemon-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm i -g nodemon
      - run: nodemon -v
